#-------------------------------------#
#              * MAGMA *              #
#         Gene set enrichment         #
#-------------------------------------#
# 1 create gene set (config generated by gwas summary)
magma=/public/home/shilulu/software/MAGMA_v1.10/magma
eur="/public/share/wchirdzhq2022/Wulab_share/1000GenomePhase3_Ref_hg37/g1000_eur/g1000_eur"
geneloc="/public/home/shilulu/software/MAGMA_v1.10/NCBI37.3.SYMB.gene.loc"
prefix=$(basename "$eur")

#- gene annotation
qsubshcom "$magma --annotate window=35,10 \
--snp-loc $eur.bim \
--gene-loc $geneloc \
--out $prefix" 1 100G magma 1:00:00 ""

#- SNP p extract
gwas="/public/home/shilulu/Wulab/sll/ARHL/NC_sup_test/01.meta/All_MVP_Trpchevska_De-Angelis_BBJ_filter.txt"
trait="ARHL"
awk 'NR > 1 {print $1"\t"$7"\t"$8}' $gwas > $trait.pval

#- gene-based association study
qsubshcom "$magma --bfile $eur \
--pval $trait.pval ncol=3 \
--gene-annot $prefix.genes.annot
--out $trait" 1 100G magma 1:00:00 ""

# 2 run gene-based enrichment
magma=/public/home/shilulu/software/MAGMA_v1.10/magma
generaw="/public/home/shilulu/Wulab_project/ARHL/NC_sup_test/08.scEnrich/config/ARHL.genes.raw"
trait="ARHL"

declare -A cells=(
    ["Eshel"]="/public/home/shilulu/Wulab_project/ARHL/NC_sup_test/08.scEnrich/Eshel/MAGMA"
    ["Milon"]="/public/home/shilulu/Wulab_project/ARHL/NC_sup_test/08.scEnrich/Milon/MAGMA"
    ["Ranum"]="/public/home/shilulu/Wulab_project/ARHL/NC_sup_test/08.scEnrich/Ranum/MAGMA"
    ["Jean"]="/public/home/shilulu/Wulab_project/ARHL/NC_sup_test/08.scEnrich/Jean/MAGMA"
    ["Sun1_2"]="/public/home/shilulu/Wulab_project/ARHL/NC_sup_test/08.scEnrich/Sun/1-2M/MAGMA"
    ["Sun12_15"]="/public/home/shilulu/Wulab_project/ARHL/NC_sup_test/08.scEnrich/Sun/12-15M/MAGMA"
    ["Sun5"]="/public/home/shilulu/Wulab_project/ARHL/NC_sup_test/08.scEnrich/Sun/5M/MAGMA"
    ["Xu"]="/public/home/shilulu/Wulab_project/ARHL/NC_sup_test/08.scEnrich/Xu/MAGMA"
    ["Iyer"]="/public/home/shilulu/Wulab_project/ARHL/NC_sup_test/08.scEnrich/Iyer/MAGMA")

for wkdir in "${!cells[@]}"; do
    dir="${cells[$wkdir]}"
    qsubshcom "$magma --gene-results $generaw --set-annot $dir/top10.txt --out $dir/$trait" 1 100G magma 1:00:00 ""
done


