# METAL Options:
SCHEME STDERR
AVERAGEFREQ ON
MINMAXFREQ ON
VERBOSE OFF
# Input columns:
CHROMOSOME CHR
MARKER SNP
ALLELE A1 A2
EFFECT beta
STDERR SE
FREQ freq
PVALUE p
WEIGHT N
GENOMICCONTROL OFF

ADDFILTER freq > 0.01
ADDFILTER freq < 0.99
TRACKPOSITIONS ON 
CHROMOSOME CHR
POSITION POS
# additional options
EFFECT_PRINT_PRECISION 12
STDERR_PRINT_PRECISION 12
CUSTOMVARIABLE TotalSampleSize  
LABEL TotalSampleSize as N

PROCESS /public/home/shilulu/Wulab/sll/ARHL/NC_sup_test/01.meta/EUR_MVP_Trpchevska_De-Angelis_METALfilter.gz
PROCESS /public/share/wchirdzhq2022/Wulab_share/GWAS-summary/MVP/hearing-loss/MVP_AFR_reformat.gz
PROCESS /public/share/wchirdzhq2022/Wulab_share/GWAS-summary/MVP/hearing-loss/MVP_AMR_reformat.gz
PROCESS /public/home/shilulu/Wulab/sll/ARHL/NC_sup_test/01.meta/EAS_MVP_BBJ_METALfilter.gz

OUTFILE All_MVP_Trpchevska_De-Angelis_BBJ .tbl
ANALYZE HETEROGENEITY 
QUIT 


